---
development:
  cloud_name: suryast
  api_key: '149568663171371'
  api_secret: HwduTnUTEkHqESdeTBIkcKPdXXI
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: suryast
  api_key: '149568663171371'
  api_secret: HwduTnUTEkHqESdeTBIkcKPdXXI
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: suryast
  api_key: '149568663171371'
  api_secret: HwduTnUTEkHqESdeTBIkcKPdXXI
  enhance_image_tag: true
  static_image_support: false
